/* 
---------------- !! ESTE APARTADO NO TIENE STORE DEBIDO A QUE EL MODULO USUARIOS A LA HORA DE CREAR UNO NUEVO NOS PERMITE ELIGIR EL TIPO DE USUARIO 
AL CUAL HACEMOS REFERENCIA 
YA SEA PACIENTE, EMPLEADO ETC, POR TAL MOTIVO NO SE CREA DIRECTAMENTE UN EMPLEADO SI NO UN USUARIO CON SU ROL ----------- !! */